#!/bin/bash
set -euo pipefail

if [[ -z "${ECR_REGISTRY}" ]]; then
    echo "The env var ECR_REGISTRY must be set"
    exit 1
fi

function exit_and_fail() {
    echo "❌ Failed to login to ECR Public Repo!"
}

trap exit_and_fail INT TERM ERR

docker run --rm \
    -e AWS_REGION=${AWS_REGION:=""} \
    -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:=""} \
    -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:=""} \
    -e AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN:=""} \
    -e AWS_PAGER="" \
    amazon/aws-cli ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${ECR_REGISTRY}
