name: pg

on: [workflow_dispatch]

env:
  DEFAULT_GO_VERSION: ^1.15

jobs:

  releaseWindows:
    name: Release Windows
    runs-on: windows-2019
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.DEFAULT_GO_VERSION }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Release Windows Assets
      run: ls /
